### ISSUE TITLE
Queries including multiplicative boosts not explained correctly

### ISSUE THREAD

**Issue by wrigleyDan** [o19s/splainer-search#125]
It looks like Solr changed the explanation of the score when using multiplicative boost functions via boost parameter somewhere between Solr 4.6 and Solr 8.11.

Only the first part of the explain output is interpreted and shown in Splainer:
![image](https://github.com/o19s/splainer-search/assets/54574577/3c0a1df2-bf72-4d46-96e0-267137f871ec)

When changing to an additive boost function everything works properly again:
![image](https://github.com/o19s/splainer-search/assets/54574577/c71b658d-4369-491d-913f-688f7a1a0436)

Ways to reproduce the issue:
Here is a link to a Splainer example: http://splainer.io/#?solr=http:%2F%2Fquepid-solr.dev.o19s.com:8985%2Fsolr%2Ftmdb%2Fselect%3Fq%3Drambo%26defType%3Dedismax%26boost%3Dsum(vote_count,0)%26fl%3Dtitle%20overview&fieldSpec=title,%20overview

The detailed score output only shows the very first part of the score explanation:
```13972.80162024498 weight(FunctionScoreQuery(text_all:rambo, scored by boost(sum(int(vote_count),const(0))))), result of:```

The rest is discarded and it seems not processed.

Presumably the fix for this is somewhere in here: https://github.com/o19s/splainer-search/blob/main/services/explainSvc.js

As older Solr versions are working with the current Splainer implementation a fix should not change the current behavior.

**Comment by epugh** [comment]
Fixed a while ago!
