### ISSUE TITLE
Search engine searchapi does not support retrieving per doc metadata directly

### ISSUE THREAD

**Issue by dacox** [o19s/splainer-search#140]
**Describe the bug**
When using the `searchapi` searchengine, I get the following error:

> Search engine searchapi does not support retrieving per doc metadata directly

**To Reproduce**

Using the newly pushed docker image released after https://github.com/o19s/quepid/issues/890

https://hub.docker.com/layers/o19s/quepid/latest/images/sha256-bb94695eb976fa83e51c71c49436e9da3063d720607ed9961aca7c8399e372a7

Load a Case that uses `searchapi` - the case never loads results.

```
Name: None specified, using generated name

Search engine:  searchapi

Endpoint url: http://name-of-internal-service/search/

Custom headers: { "Authorization": "Token BLAHBLAHBLAH", "Accept": "application/json", "Content-Type": "application/json", "FOO": "BAR"}

API method: POST

Proxy Requests: true

Basic Auth Credential: 0

Options:

Custom Code Mapper:

numberOfResultsMapper = function(data){
  return data.length
};

docsMapper = function(data){...
```

**Expected behavior**

The case should not error

**Screenshots**

<img width="987" alt="Screenshot 2023-11-30 at 11 32 04 AM" src="https://github.com/o19s/quepid/assets/3887682/de96c5d5-a10e-49b1-ad51-40f1f780b181">

**Additional context**

I have tracked it down to https://github.com/o19s/splainer-search/commit/9034c0bb86a42828a66efc4badcae0e687302b23

**Comment by epugh** [comment]
This was fixed in #141...    If it itsn't working for you, please reopen this ticket!
