### ISSUE TITLE
Feature Request: Algolia Integration

### ISSUE THREAD

**Issue by sumitsarkar** [o19s/splainer-search#144]
**Feature Description:**
Add support for Algolia in the Splainer-Search library.

**Rationale:**
Many developers, including myself, use [Algolia](https://www.algolia.com/) for search functionalities. Integrating Algolia into Splainer-Search would be beneficial for debugging and optimizing Algolia search queries, expanding the tool's utility.

**Implementation Consideration:**
This would involve adapting the library to work with Algolia's API, ensuring compatibility with current functionalities for Elasticsearch and Solr. 

I have a working version for splainer-search already with Algolia. It is similar to Search API, and takes away some of the extra work needed to configure within Quepid. If the maintainers are open to the idea, I am open to raising a merge request.

**Comment by epugh** [comment]
Woot!   I would love to see a PR...!   We added Vectara not that long ago, which kind of opened the door to more non-Lucene search engines.  

Out of curiosity, is there a public Algolia server that we could use for integration/system testing of the code?   Similar to these that we have for [OS](https://github.com/o19s/quepid/wiki/Troubleshooting-Opensearch-and-Quepid), [ES](https://github.com/o19s/quepid/wiki/Troubleshooting-Elasticsearch-and-Quepid), and [Solr](https://github.com/o19s/quepid/wiki/Troubleshooting-Solr-and-Quepid).  Not a requirement, but just a way to make sure as we evolve and change things that the integration continues to work ;-).

**Comment by sumitsarkar** [comment]
Thanks for the super quick reply Eric! I'll try to get a PR submitted tomorrow.

There are public Algolia demos that we can use for integration testing. Some of them are listed here:
https://www.algolia.com/doc/guides/building-search-ui/resources/demos/js/

But I don't think they are guaranteed to be available under the same URL or have the same index names.
