### ISSUE TITLE
Escape field name to avoid splitting on `:`

### ISSUE THREAD

**Issue by ychaker** [o19s/splainer-search#52]
create a way to escape the name, would surrounding it by "  
For example: id:_id title:title "do_not:split_me"  
it assumes that no field would have the "  character in it, so we would strip them out of the name but won't split it on the : 

see https://app.intercom.io/a/apps/i869mnw9/respond/inbox/all/conversations/11058679737 for reference

**Comment by epugh** [comment]
This is old issue, and while I'd love to see a fix for this, I want to close out old tickets that aren't getting traction ;-).
