### ISSUE TITLE
Support displaying JS object fields

### ISSUE THREAD

**Issue by ychaker** [o19s/splainer-search#61]

**Comment by epugh** [comment]
@ychaker is this a splainer-search issue, or is this higher up at the Quepid or Splainer project level?   Do you have some thoughts on what we should do at this level?   There is some work at the Quepid level, and this bug shows up on splainer.io as well (http://splainer.io/#/es_?esUrl=http:%2F%2Fquepid-elasticsearch.dev.o19s.com:9200%2Ftmdb%2F_search&esQuery=%7B%0D%0A%09%22query%22:%20%7B%0D%0A%09%09%22bool%22:%20%7B%0D%0A%09%09%09%22should%22:%20%5B%0D%0A%09%09%09%09%7B%0D%0A%09%09%09%09%09%22multi_match%22:%20%7B%0D%0A%09%09%09%09%09%09%22query%22:%20%22star%20wars%22,%0D%0A%09%09%09%09%09%09%22type%22:%20%22cross_fields%22,%0D%0A%09%09%09%09%09%09%22fields%22:%20%5B%0D%0A%09%09%09%09%09%09%09%22title%22,%0D%0A%09%09%09%09%09%09%09%22tagline%22,%0D%0A%09%09%09%09%09%09%09%22overview%22%0D%0A%09%09%09%09%09%09%5D%0D%0A%09%09%09%09%09%7D%0D%0A%09%09%09%09%7D,%0D%0A%09%09%09%09%7B%0D%0A%09%09%09%09%09%22bool%22:%20%7B%0D%0A%09%09%09%09%09%09%22filter%22:%20%7B%0D%0A%09%09%09%09%09%09%09%22match_phrase%22:%20%7B%0D%0A%09%09%09%09%09%09%09%09%22text_people_notf_front%22:%20%7B%0D%0A%09%09%09%09%09%09%09%09%09%22query%22:%20%22star%20wars%22%0D%0A%09%09%09%09%09%09%09%09%7D%0D%0A%09%09%09%09%09%09%09%7D%0D%0A%09%09%09%09%09%09%7D,%0D%0A%09%09%09%09%09%09%22should%22:%20%5B%0D%0A%09%09%09%09%09%09%09%7B%0D%0A%09%09%09%09%09%09%09%09%22multi_match%22:%20%7B%0D%0A%09%09%09%09%09%09%09%09%09%22fields%22:%20%5B%0D%0A%09%09%09%09%09%09%09%09%09%09%22cast%5E10%22,%0D%0A%09%09%09%09%09%09%09%09%09%09%22directors%22%0D%0A%09%09%09%09%09%09%09%09%09%5D,%0D%0A%09%09%09%09%09%09%09%09%09%22query%22:%20%22star%20wars%22%0D%0A%09%09%09%09%09%09%09%09%7D%0D%0A%09%09%09%09%09%09%09%7D%0D%0A%09%09%09%09%09%09%5D%0D%0A%09%09%09%09%09%7D%0D%0A%09%09%09%09%7D,%0D%0A%09%09%09%09%7B%0D%0A%09%09%09%09%09%22function_score%22:%20%7B%0D%0A%09%09%09%09%09%09%22query%22:%20%7B%0D%0A%09%09%09%09%09%09%09%22match_phrase%22:%20%7B%0D%0A%09%09%09%09%09%09%09%09%22title%22:%20%7B%0D%0A%09%09%09%09%09%09%09%09%09%22query%22:%20%22star%20wars%22%0D%0A%09%09%09%09%09%09%09%09%7D%0D%0A%09%09%09%09%09%09%09%7D%0D%0A%09%09%09%09%09%09%7D,%0D%0A%09%09%09%09%09%22field_value_factor%22:%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22field%22:%20%22vote_count%22,%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22factor%22:%201,%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22missing%22:%201%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%09%09%09%09%09%7D%0D%0A%09%09%09%09%7D%0D%0A%09%09%09%5D%0D%0A%09%09%7D%0D%0A%09%7D%0D%0A%7D&fieldSpec=*%20cast.character)

**Comment by epugh** [comment]
This is an old ticket, and there are some other tickets out there that may have replaced this, so closing it out.  Please reopen if you think it still needs to be addressed!
